### PR TITLE
Initial support for secrets for object storage datasets

### PR DESCRIPTION
**Pull request by srikumar003**
Adding functionality to supply auth info for S3/COS datasets using secrets

Instead of:
` accessKeyID: "{AWS_ACCESS_KEY_ID}"`
` secretAccessKey: "{AWS_SECRET_ACCESS_KEY}"`

the user can provide:
`secret-name: "{SECRET_NAME}"`
`secret-namespace: "{SECRET_NAMESPACE}"` 

secret-namespace is optional if the secret is defined in the same namespace as the dataset

### CODE REVIEW

**Comment by YiannisGkoufas** [comment]
Thanks @srikumar003 ! one quick comment. maybe for the time being we should only have reference to the same namespace?
Because in that case the `useas: "configmap"` breaks as it won't find the Secret to mount in the pod

**Comment by srikumar003** [comment]
Accessing secrets from another namespace works for DLF with the following 

`$ kubectl create ns test`
`$ kubectl create -f examples/templates/example-s3-secret.yaml -n test`

Change the dataset definition file `examples/templates/example-dataset-s3-secrets.yaml` to refer to the `s3secrets` in `test` namespace like so:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
  namespace: default
spec:
  local:
    type: "COS"
    secret-name: "s3secret" #see s3-secrets.yaml for an example
    secret-namespace: "test" #optional if the secret is in the same ns as dataset
    endpoint: "endpoint_url"
    bucket: "bucket_name"
    readonly: "true" # default is false
    region: "" #it can be empty
```

Create the dataset:
`$ kubectl create -f examples/templates/example-dataset-s3-secrets.yaml -n default`

Verify:
`$ kubectl get pvc`
`$ kubectl get cm`

Should give the PVC and the ConfigMap

**Comment by YiannisGkoufas** [comment]
looks good!

**Comment by TobiasGoerke** [comment]
When using `secret-namespace` the referenced secret (likely residing in another namespace) is being copied to the dataset's namespace. Is this by design? This may be a huge security risk if users can use datashim to obtain access to secrets in other namespaces..

**Comment by srikumar003** [comment]
@TobiasGoerke  Indeed, you are correct. We create a new secret to use the dataset in config map mode where the secret information is passed into a pod as a set of environment variables. But, when the secret is another namespace, we will end up copying it over. 

Thanks for pointing this out. Could you please create an issue with the text above and we'll create a fix for it

**Pull request merged**
